### ISSUE TITLE
Hapi static assets

### ISSUE THREAD

**Issue by lynnaloo** [rachelnicole/robokitty#34]
I can't test this because I I don't have my Photon handy, but you could replace those four existing Hapi routes in `lib/server.js` with this one route to handle the static content in that `public` directory:

```
    server.route({
      method: 'GET',
      path: '/{param*}',
      handler: {
        directory: {
          path: 'public',
          listing: false,
          index: true
        }
      }
    });

```

It should basically work the same way, but I'm making the assumption that you just want to serve up that content and that it isn't required to link directly to your image assets.

**Comment by MilanLoveless** [comment]
@lynnaloo does `npm test` result in passing tests?

**Comment by lynnaloo** [comment]
Yes, if I comment out the Photon dependency (and fix the typo I had above :smirk_cat:). I'll do a PR so you can try it out.

**Comment by rachelnicole** [comment]
Looks fantastic, thank you so much ^_^
